### ISSUE TITLE
Nav bar in homepage is different from otherpages.

### ISSUE THREAD

**Issue by aswinastha** [rohanns7/Hotel-Booking-System#11]
![Screenshot_52](https://user-images.githubusercontent.com/81344507/118389235-a067f480-b648-11eb-9df5-1c1447d46dee.png)
The context of nav bar is diff

**Comment by Bikash0081** [comment]
Go to Css and use margin top for the heading of the webpage.

**Comment by kunga-herald** [comment]
copy css of nar bar from other pages to make it same..
keep the toggle actve for ome page on nav bar..

**Comment by aswinastha** [comment]
![Uploading Screenshot_94.png…]()

**Comment by aswinastha** [comment]
it is done. thank you!

**Comment by aswinastha** [comment]
![Screenshot_94](https://user-images.githubusercontent.com/81344507/118390937-749d3c80-b651-11eb-94af-8c1a00584d7c.png)
