### ISSUE TITLE
no book now page in accomodation

### ISSUE THREAD

**Issue by aswinastha** [rohanns7/Hotel-Booking-System#8]

**Comment by aayushaaryal** [comment]
Css file is not linked in html page of accomodation

**Comment by aswinastha** [comment]
@rohanns7 give the proper file location.

**Comment by rohanns7** [comment]
![Screenshot_51](https://user-images.githubusercontent.com/81344449/118386984-267d3e80-b63b-11eb-8667-9f002e38d006.png)
I have fixed the issue.
