### ISSUE TITLE
Sequnce Diagram ()

### ISSUE THREAD

**Issue by Bikash0081** [rohanns7/Hotel-Booking-System#9]
Please make a condition for Booking error.
What happens if the number is incorrect?.
![issue](https://user-images.githubusercontent.com/81344604/118387646-529abe80-b63f-11eb-8be4-b7519f9564c0.png)

**Comment by aswinastha** [comment]
![185793400_255312553009096_5487213236185414153_n](https://user-images.githubusercontent.com/81344507/118387791-259adb80-b640-11eb-997f-e841a13a9847.png)
Condition bugs is added for phone number error.

**Comment by aswinastha** [comment]
![185793400_255312553009096_5487213236185414153_n](https://user-images.githubusercontent.com/81344507/118387860-875b4580-b640-11eb-9329-08487ac67d29.png)
Condition box is added for phone number error.

**Comment by Bikash0081** [comment]
Thank You for solving issue
